### ISSUE TITLE
Add pip to the container so it is possible to use python libraries

### ISSUE THREAD

**Issue by EinarElen** [floridop/mnxb11-container#3]
In one of the exercises we are using a python script created by an LLM to generate some data for us, which we then use C++ to analyze to see if the LLM script was doing the right thing. The LLM script requires numpy which can be installed with pip on a user level but we don't have pip in the container right now

Alternatively we could just bake in numpy

**Comment by EinarElen** [comment]
On second thought, I think the numpy approach is going to be better

**Comment by floridop** [comment]
I think I will also add pip and venv to provide a more versatile container.
